#! /bin/sh

CLASSPATH="$CLASSPATH:$HOME/.local/share/java/java-cup-11b.jar"
CLASSPATH="$CLASSPATH:$HOME/.local/share/java/java-cup-11b-runtime.jar"
export CLASSPATH

exec /usr/bin/java java_cup.Main "$@"